/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SurveyController;

/**
 *
 * @author ACER
 */
public class UpdateSurvey extends javax.swing.JFrame {

    /**
     * Creates new form UpdateSurvey
     */
    public UpdateSurvey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Survey_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Question_no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Question = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Response_type = new javax.swing.JComboBox<>();
        Option_1 = new javax.swing.JTextField();
        Option_3 = new javax.swing.JTextField();
        Option_4 = new javax.swing.JTextField();
        Option_2 = new javax.swing.JTextField();
        Save_update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Survey_Name.setBackground(new java.awt.Color(0, 0, 0));
        Survey_Name.setForeground(new java.awt.Color(255, 255, 255));
        Survey_Name.setText("a");
        Survey_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Survey_NameActionPerformed(evt);
            }
        });
        getContentPane().add(Survey_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 105, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 51));
        jLabel1.setText("Survey Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 140, -1));

        jLabel2.setText("=");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 72, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 51));
        jLabel3.setText("Question No :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        jLabel4.setText("=");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 109, -1, -1));

        Question_no.setBackground(new java.awt.Color(0, 0, 0));
        Question_no.setForeground(new java.awt.Color(255, 255, 255));
        Question_no.setText("hh");
        getContentPane().add(Question_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 71, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 51));
        jLabel5.setText("Question    :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 150, -1));

        Question.setBackground(new java.awt.Color(0, 0, 0));
        Question.setForeground(new java.awt.Color(255, 255, 255));
        Question.setText("Enter the question !");
        getContentPane().add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 440, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 51));
        jLabel6.setText("Response Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        Response_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radio Button", "Suyog", "Nihira", "Prasanna" }));
        Response_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Response_typeActionPerformed(evt);
            }
        });
        getContentPane().add(Response_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        Option_1.setBackground(new java.awt.Color(0, 0, 0));
        Option_1.setForeground(new java.awt.Color(0, 255, 51));
        Option_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 255, 0), null, null));
        getContentPane().add(Option_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 230, 40));

        Option_3.setBackground(new java.awt.Color(0, 0, 0));
        Option_3.setForeground(new java.awt.Color(0, 255, 51));
        Option_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 255, 51), null, null));
        getContentPane().add(Option_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 230, 40));

        Option_4.setBackground(new java.awt.Color(0, 0, 0));
        Option_4.setForeground(new java.awt.Color(0, 255, 51));
        Option_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 255, 51), null, null));
        Option_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option_4ActionPerformed(evt);
            }
        });
        getContentPane().add(Option_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 230, 40));

        Option_2.setBackground(new java.awt.Color(0, 0, 0));
        Option_2.setForeground(new java.awt.Color(0, 255, 51));
        Option_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 255, 51), null, null));
        getContentPane().add(Option_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 230, 40));

        Save_update.setBackground(new java.awt.Color(0, 0, 0));
        Save_update.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        Save_update.setForeground(new java.awt.Color(0, 255, 51));
        Save_update.setText("SAVE");
        Save_update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 51), 1, true));
        Save_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_updateActionPerformed(evt);
            }
        });
        getContentPane().add(Save_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 100, 40));

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 255, 51));
        reset.setText("RESET");
        reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 255, 51), null, new java.awt.Color(0, 255, 0)));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 110, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Update        Survey");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 350, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Pictures\\Saved Pictures\\Frame 2.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 250, 110));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Pictures\\Saved Pictures\\Desktop - 6.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Survey_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Survey_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Survey_NameActionPerformed

    private void Response_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Response_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Response_typeActionPerformed

    private void Option_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option_4ActionPerformed

    private void Save_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_updateActionPerformed
    String survey_name = Survey_Name.getText();
    int question_no =  Integer.parseInt(Question_no.getText());
    String question = Question.getText();
    String option_1 = Option_1.getText();
    String option_2 = Option_2.getText();
    String option_3 = Option_3.getText();
    String option_4 = Option_4.getText();
    SurveyController sc = new SurveyController();
    sc.updateSurvey(question,survey_name,question_no,option_1,option_2,option_3,option_4);
    

    }//GEN-LAST:event_Save_updateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSurvey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSurvey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Option_1;
    private javax.swing.JTextField Option_2;
    private javax.swing.JTextField Option_3;
    private javax.swing.JTextField Option_4;
    private javax.swing.JTextField Question;
    private javax.swing.JTextField Question_no;
    private javax.swing.JComboBox<String> Response_type;
    private javax.swing.JButton Save_update;
    private javax.swing.JTextField Survey_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
